services:
  uovotrappola:
    image: matt3010/uovotrappola:latest
    container_name: uovotrappola_bot
    restart: always
    env_file: .env
    volumes:
      - ./trappola.db:/usr/src/app/trappola.db